
kind: pipeline
name: amd64-build

platform:
  arch: amd64

steps:
- name: core
  image: clang-nasm-gmake
  pull: never
  commands:
  - make root ARCH=amd64 BINDIR=bintmp

- name: modules
  image: clang-nasm-gmake
  pull: never
  commands:
  - make modules ARCH=amd64 BINDIR=bintmp

