
kind: pipeline
name: amd64-build

platform:
  arch: amd64

steps:
- name: init
  image: drone/git
  commands:
  - mkdir bintmp
  - git submodule update --recursive --remote

- name: core
  image: clang-nasm-gmake
  pull: never
  commands:
  - make root ARCH=amd64 BINDIR=bintmp
  depends_on:
  - init

- name: modules
  image: clang-nasm-gmake
  pull: never
  commands:
  - make modules ARCH=amd64 BINDIR=bintmp
  depends_on:
  - init

---

kind: pipeline
name: i386-build

platform:
  arch: amd64

steps:
- name: init
  image: drone/git
  commands:
  - mkdir bintmp
  - git submodule update --recursive --remote

- name: core
  image: clang-nasm-gmake
  pull: never
  commands:
  - make root ARCH=i386 BINDIR=bintmp
  depends_on:
  - init

- name: modules
  image: clang-nasm-gmake
  pull: never
  commands:
  - make modules ARCH=i386 BINDIR=bintmp
  depends_on:
  - init



